### ISSUE TITLE
P0011 ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by meta-system** [meta-system/projectEuler#2]
My solution to [problem 11](https://projecteuler.net/problem=11) throws an ArrayIndexOutOfBoundsException at [main(60)](https://github.com/meta-system/projectEuler/blob/develop/src/projectEuler/P0011.java#L60).
Please help!

**Comment by BurningKarl** [comment]
The error is in line 75. Replace j-k by j+k.

Explanation:
Look at the paragraph "//diagonal lu -> ro"
If j = 0 and k = 3, your index j-k is negative. That's why the IndexOutOfBoundsException gets thrown. As you said in your comment, you want the product of a row of numbers, that start in the lower left corner and end in the upper right corner. Therefore your row index i has to be decremented and your column index j has to be incremented.

**Comment by BurningKarl** [comment]
The problem you ran into is, that the condition in your for-loops with j is wrong. It is: i < myNumbs[i].length, but it should be j < myNumbs[i].length. As i does not change in the inner for-loop j gets increased infinitely and therefore you get an IndexOutOfBoundsException.

Hope this helps :)
Gn

**Comment by meta-system** [comment]
Thanks everybody for your help.
Hey Karl! ;-)
